### ISSUE TITLE
Publish unlighthouse image

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/ddev-unlighthouse#4]
Currently, unlighthouse image is created through a Dockerfile: https://github.com/Metadrop/ddev-unlighthouse/blob/main/unlighthouseBuild/Dockerfile

The problem of this is that the images are constructed from scratch at every user local environment, which sometimes may lead to slow project startup (ddev start).

I propose publishing an image in docker hub.

**Comment by juanjol** [comment]
This is now fixed, we are using this image https://github.com/Metadrop/docker-unlighthouse Thanks @omarlopesino !!
